id: I67B1441E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:32:46+00:00'
last_modified: '2022-06-07T16:07:35.005559+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21914
  title: སྤྱོད་འཇུག་རྩ་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8DFF:
      image_group_id: I5058
      title: ''
      total_pages: 466
      order: 1
      base_file: 8DFF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
